# 0x05. Python - Exceptions

## Description
Errors and Exceptions

## Table of contents

Files | Description
----------- | -----------
[.gitignore](./.gitignore) | Ignore test files
[0-safe_print_list.py](./0-safe_print_list.py) | Function that prints x elements of a list. Prototype: def safe_print_list(my_list=[], x=0):
[1-safe_print_integer.py](./1-safe_print_integer.py) | function that prints an integer with "{:d}".format(). Prototype: def safe_print_integer(value):
[2-safe_print_list_integers.py](./2-safe_print_list_integers.py) | function that prints the first x elements of a list and only integers. Prototype: def safe_print_list_integers(my_list=[], x=0):
[3-safe_print_division.py](./3-safe_print_division.py) | function that divides 2 integers and prints the result. Prototype: def safe_print_division(a, b):
[4-list_division.py](./4-list_division.py) | Function that divides element by element 2 lists. Prototype: def list_division(my_list_1, my_list_2, list_length):
[5-raise_exception.py](./5-raise_exception.py) | Function that raises a type exception. Prototype: def raise_exception():
[6-raise_exception_msg.py](./6-raise_exception_msg.py) | Function that raises a name exception with a message. Prototype: def raise_exception_msg(message=""):
[100-safe_print_integer_err.py](./100-safe_print_integer_err.py) | Function that prints an integer. Prototype: def safe_print_integer_err(value):
[101-safe_function.py](./101-safe_function.py) | Function that executes a function safely. Prototype: def safe_function(fct, *args):
[9. ByteCode -> Python #4](./102-magic_calculation.py) | Python function def magic_calculation(a, b): 
[10. CPython #2: PyFloatObject](./103-python.c) | Prototype: void print_python_list(PyObject *p); Prototype: void print_python_bytes(PyObject *p); Prototype: void print_python_float(PyObject *p);
